@extends('layouts.app')
@section('content')

        {{-- ************************************************
         This file is generated by SNOOBIX on May 16, 2024
         Please visit snoobix.com for more details
         *********************************************** --}}

    <div class="page-content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <form action="{{route('backend.blog_posts.'.$submit_path)}}" method="POST" ENCTYPE="multipart/form-data">
                        @csrf
                        <div class="card-header">
                            <div class="row" >
                                <div class="col-3 text-start">
                                    <div class="page-title-box d-flex align-items-center justify-content-between">
                                        <h4 class="card-title">{{ucwords($module_title)}} </h4>
                                    </div>
                                </div>
                                <div class="col-6 text-center">
                                    @if(session('flash_success') != '')
                                        <div class="alert alert-success">{{session('flash_success')}}</div>
                                    @endif
                                    @if(session('flash_failure') != '')
                                        <div class="alert alert-danger">{{session('flash_failure')}}</div>
                                    @endif
                                </div>
                                <div class="col-3 text-end">
                                    <a href="{{route('backend.blog_posts')}}" class="btn btn-info btn-md"  >List Page</a>
                                </div> 
                            </div>
                        </div>
                        <div class="card-body">
                            
                            <div class="row">
                                <div class="col-lg-12">
                                
                                        
                                            <div class="row"> 

                                                    
		<input
			type="hidden"
			id="id"
			name="id"
			value="@if(isset($row->id)) {{ $row->id }} @endif"
		/>
		



		<input
			type="hidden"
			id="user_id"
			name="user_id"
			value="@if(isset($row->user_id)) {{ $row->user_id }} @endif"
		/>
		



		<input
			type="hidden"
			id="web_user_id"
			name="web_user_id"
			value="@if(isset($row->web_user_id)) {{ $row->web_user_id }} @endif"
		/>
		


<div class="col-md-6 mt-3">
	<div class="form-group">
    <label class="form-label" for="blog_category_id">BLOG CATEGORY</label>

@php
    
    if(!Empty($row)){ 
        $selected = $row->blog_category_id; 
    }else{
        $selected = '';
    }
    $options = get_list_values('blog_categories','blog_category');
    //pre($options);
	//$options = $blog_category_id;
 @endphp

		 <select class="form-control" name="blog_category_id" id="blog_category_id"> 
		   <option value="">--Select--</option>
		   @foreach ($options as $key => $value)
			<option value="{{$key}}" {{($key == $selected) ? 'selected' : '' }}> 
				{{$value}} 
			</option>
		  @endforeach    
		</select>

 </div>
 <div id="diverr_blog_category_id" text-danger></div>
</div>

<div class="col-md-6 mt-3">
	<div class="form-group">
		<label class="form-label" for="blog_title">BLOG TITLE</label>
		<input
			type="text"
			id="blog_title"
			name="blog_title"
			class="form-control"
			value="@if(isset($row->blog_title)){{$row->blog_title}}@endif"
			
		/>
	</div>
	<div id="diverr_blog_title" text-danger></div>
</div>


<div class="col-md-6 mt-3">
	<div class="form-group">
		<label class="form-label" for="blog_image">BLOG IMAGE</label>
		<input
			type="file"
			id="blog_image"
			name="blog_image"
			class="form-control"
			
			>

			<div>
				@if(isset($row) && !Empty($row))
					<img src="{{url('storage/'.str_replace('public/','',$row->blog_image))}}" width="200px" height="250px" />                                                    
				@endif
			</div>

	</div>
	<div id="diverr_blog_image" text-danger></div>
</div>


<div class="col-md-12 mt-3">
	<div class="form-group">
		<label class="form-label" for="blog_text">BLOG TEXT</label>
		
		<textarea
			id="blog_text"
			name="blog_text"
			class="form-control"			
			
			>@if(isset($row->blog_text)){{$row->blog_text}}@endif</textarea>
			<script>
				CKEDITOR.replace('blog_text');				
			</script>
	</div>
	<div id="diverr_blog_text" text-danger></div>
</div>

<div class="col-md-6 mt-3">
	<div class="form-group">
    <label class="form-label" for="active">ACTIVE</label>

@php
    
    if(!Empty($row)){ 
        $selected = $row->active; 
    }else{
        $selected = '';
    }
    $options = get_list_values('active_status','is_active');
    //pre($options);
	//$options = $active;
 @endphp

		 <select class="form-control" name="active" id="active"> 
		   <option value="">--Select--</option>
		   @foreach ($options as $key => $value)
			<option value="{{$key}}" {{($key == $selected) ? 'selected' : '' }}> 
				{{$value}} 
			</option>
		  @endforeach    
		</select>

 </div>
 <div id="diverr_active" text-danger></div>
</div>

                                                
                                            </div>
                                            
                                            <input type="hidden" name="continue" id="continue" value="Y" />
                                            <input type="hidden" name="id" id="id" value="@if(isset($row->id)) {{id2str($row->id)}} @endif" />
                                            
                                </div>
                            </div>
                        </div>

                        <div class="card-footer">
                            <div class="row " > 
                                <div class="col-md-6 text-start mt-2">
                                    <button type="submit" class="btn btn-primary waves-effect waves-light w-md">Submit</button>
                                </div>
                                <div class="col-md-6 text-end  mt-2">
                                    <button type="reset" class="btn btn-outline-danger waves-effect waves-light w-md">Reset</button>
                                </div>
                            </div>
                        </div>
                        </form>
                    </div>
                </div>
            </div>

        </div> 
    </div>


@endsection