@extends('layouts.app')
@section('content')

        {{-- ************************************************
         This file is generated by SNOOBIX on May 16, 2024
         Please visit snoobix.com for more details
         *********************************************** --}}

    <div class="page-content">
        <div class="container-fluid">

            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <form action="{{route('backend.cards.'.$submit_path)}}" method="POST" ENCTYPE="multipart/form-data">
                        @csrf
                        <div class="card-header">
                            <div class="row" >
                                <div class="col-3 text-start">
                                    <div class="page-title-box d-flex align-items-center justify-content-between">
                                        <h4 class="card-title">{{ucwords($module_title)}} </h4>
                                    </div>
                                </div>
                                <div class="col-6 text-center">
                                    @if(session('flash_success') != '')
                                        <div class="alert alert-success">{{session('flash_success')}}</div>
                                    @endif
                                    @if(session('flash_failure') != '')
                                        <div class="alert alert-danger">{{session('flash_failure')}}</div>
                                    @endif
                                </div>
                                <div class="col-3 text-end">
                                    <a href="{{route('backend.cards')}}" class="btn btn-info btn-md"  >List Page</a>
                                </div> 
                            </div>
                        </div>
                        <div class="card-body">
                            
                            <div class="row">
                                <div class="col-lg-12">
                                
                                        
                                            <div class="row"> 

                                                    
		<input
			type="hidden"
			id="id"
			name="id"
			value="@if(isset($row->id)) {{ $row->id }} @endif"
		/>
		



		<input
			type="hidden"
			id="user_id"
			name="user_id"
			value="@if(isset($row->user_id)) {{ $row->user_id }} @endif"
		/>
		



		<input
			type="hidden"
			id="web_user_id"
			name="web_user_id"
			value="@if(isset($row->web_user_id)) {{ $row->web_user_id }} @endif"
		/>
		



<div class="col-md-6 mt-3">
	<div class="form-group">
		<label class="form-label" for="title">CARD TITLE</label>
		<input
			type="text"
			id="title"
			name="title"
			class="form-control"
			value="@if(isset($row->title)){{$row->title}}@endif"
			
		/>
	</div>
	<div id="diverr_title" text-danger></div>
</div>


<div class="col-md-6 mt-3">
	<div class="form-group">
		<label class="form-label" for="short_descr">SHORT DESCR</label>
		<input
			type="text"
			id="short_descr"
			name="short_descr"
			class="form-control"
			value="@if(isset($row->short_descr)){{$row->short_descr}}@endif"
			
		/>
	</div>
	<div id="diverr_short_descr" text-danger></div>
</div>

<div class="col-md-6 mt-3">
	<div class="form-group">
    <label class="form-label" for="tags">TAGS</label>
    
    @php
        
        if(!Empty($row)){ 
            $selected = explode(',',$row->tags); 
        }else{
            $selected = array();
        }
        $options = get_list_values('tags', 'tag');
        //$options = $[[list_name]];
    @endphp

    <select class="form-control select2 select2-multiple" multiple="multiple" name="tags[]" id="tags">
        <!-- <option value="">--Select--</option> -->
        @foreach ($options as $key => $value)
            <option value="{{$key}}" @if(in_array($key,$selected)) selected="selected" @endif > 
                {{$value}} 
            </option>
        @endforeach    
    </select>


    </div>
    <div id="diverr_tags" text-danger></div>
</div>

<div class="col-md-6 mt-3">
	<div class="form-group">
		<label class="form-label" for="short_code">SHORT CODE</label>
		<input
			type="text"
			id="short_code"
			name="short_code"
			class="form-control"
			value="@if(isset($row->short_code)){{$row->short_code}}@endif"
			
		/>
	</div>
	<div id="diverr_short_code" text-danger></div>
</div>


<div class="col-md-6 mt-3">
	<div class="form-group">
		<label class="form-label" for="card_image">CARD IMAGE</label>
		<input
			type="file"
			id="card_image"
			name="card_image"
			class="form-control"
			
			>

			<div>
				@if(isset($row) && !Empty($row))
					<img src="{{url('storage/'.str_replace('public/','',$row->card_image))}}" width="200px" height="250px" />                                                    
				@endif
			</div>

	</div>
	<div id="diverr_card_image" text-danger></div>
</div>


<div class="col-md-12 mt-3">
	<div class="form-group">
		<label class="form-label" for="card_design">CARD DESIGN</label>
		<textarea
			id="card_design"
			name="card_design"
			class="form-control"
			
			>@if(isset($row->card_design)){{$row->card_design}}@endif</textarea>
			
	</div>
	<div id="diverr_card_design" text-danger></div>
</div>

<div class="col-md-6 mt-3">
	<div class="form-group">
    <label class="form-label" for="designed_by_user_id">DESIGNED BY USER</label>

@php
    
    if(!Empty($row)){ 
        $selected = $row->designed_by_user_id; 
    }else{
        $selected = '';
    }
    $options = get_list_values('users','name');
    //pre($options);
	//$options = $designed_by_user_id;
 @endphp

		 <select class="form-control" name="designed_by_user_id" id="designed_by_user_id"> 
		   <option value="">--Select--</option>
		   @foreach ($options as $key => $value)
			<option value="{{$key}}" {{($key == $selected) ? 'selected' : '' }}> 
				{{$value}} 
			</option>
		  @endforeach    
		</select>

 </div>
 <div id="diverr_designed_by_user_id" text-danger></div>
</div>
<div class="col-md-6 mt-3">
	<div class="form-group">
    <label class="form-label" for="sender_user_id">SENDER USER</label>

@php
    
    if(!Empty($row)){ 
        $selected = $row->sender_user_id; 
    }else{
        $selected = '';
    }
    $options = get_list_values('users','name');
    //pre($options);
	//$options = $sender_user_id;
 @endphp

		 <select class="form-control" name="sender_user_id" id="sender_user_id"> 
		   <option value="">--Select--</option>
		   @foreach ($options as $key => $value)
			<option value="{{$key}}" {{($key == $selected) ? 'selected' : '' }}> 
				{{$value}} 
			</option>
		  @endforeach    
		</select>

 </div>
 <div id="diverr_sender_user_id" text-danger></div>
</div>

<div class="col-md-6 mt-3">
	<div class="form-group">
		<label class="form-label" for="sender_name">NAME ON ENVELOP</label>
		<input
			type="text"
			id="sender_name"
			name="sender_name"
			class="form-control"
			value="@if(isset($row->sender_name)){{$row->sender_name}}@endif"
			
		/>
	</div>
	<div id="diverr_sender_name" text-danger></div>
</div>


<div class="col-md-6 mt-3">
	<div class="form-group">
		<label class="form-label" for="seal_design_color">SEAL COLOR</label>
		<input
			type="text"
			id="seal_design_color"
			name="seal_design_color"
			class="form-control"
			value="@if(isset($row->seal_design_color)){{$row->seal_design_color}}@endif"
			
		/>
	</div>
	<div id="diverr_seal_design_color" text-danger></div>
</div>

<div class="col-md-6 mt-3">
	<div class="form-group">
    <label class="form-label" for="seal_design_image">SEAL DESIGN</label>

@php
    
    if(!Empty($row)){ 
        $selected = $row->seal_design_image; 
    }else{
        $selected = '';
    }
    $options = get_list_values('sound_files','title');
    //pre($options);
	//$options = $seal_design_image;
 @endphp

		 <select class="form-control" name="seal_design_image" id="seal_design_image"> 
		   <option value="">--Select--</option>
		   @foreach ($options as $key => $value)
			<option value="{{$key}}" {{($key == $selected) ? 'selected' : '' }}> 
				{{$value}} 
			</option>
		  @endforeach    
		</select>

 </div>
 <div id="diverr_seal_design_image" text-danger></div>
</div>
<div class="col-md-6 mt-3">
	<div class="form-group">
    <label class="form-label" for="background_id">BACKGROUND</label>

@php
    
    if(!Empty($row)){ 
        $selected = $row->background_id; 
    }else{
        $selected = '';
    }
    $options = get_list_values('backgrounds','title');
    //pre($options);
	//$options = $background_id;
 @endphp

		 <select class="form-control" name="background_id" id="background_id"> 
		   <option value="">--Select--</option>
		   @foreach ($options as $key => $value)
			<option value="{{$key}}" {{($key == $selected) ? 'selected' : '' }}> 
				{{$value}} 
			</option>
		  @endforeach    
		</select>

 </div>
 <div id="diverr_background_id" text-danger></div>
</div>
<div class="col-md-6 mt-3">
	<div class="form-group">
    <label class="form-label" for="envelop_design_id">ENVELOP DESIGN</label>

@php
    
    if(!Empty($row)){ 
        $selected = $row->envelop_design_id; 
    }else{
        $selected = '';
    }
    $options = get_list_values('envelop_designs','title');
    //pre($options);
	//$options = $envelop_design_id;
 @endphp

		 <select class="form-control" name="envelop_design_id" id="envelop_design_id"> 
		   <option value="">--Select--</option>
		   @foreach ($options as $key => $value)
			<option value="{{$key}}" {{($key == $selected) ? 'selected' : '' }}> 
				{{$value}} 
			</option>
		  @endforeach    
		</select>

 </div>
 <div id="diverr_envelop_design_id" text-danger></div>
</div>
<div class="col-md-6 mt-3">
	<div class="form-group">
    <label class="form-label" for="envelop_inside_id">ENVELOP INSIDE</label>

@php
    
    if(!Empty($row)){ 
        $selected = $row->envelop_inside_id; 
    }else{
        $selected = '';
    }
    $options = get_list_values('envelop_inside_images','title');
    //pre($options);
	//$options = $envelop_inside_id;
 @endphp

		 <select class="form-control" name="envelop_inside_id" id="envelop_inside_id"> 
		   <option value="">--Select--</option>
		   @foreach ($options as $key => $value)
			<option value="{{$key}}" {{($key == $selected) ? 'selected' : '' }}> 
				{{$value}} 
			</option>
		  @endforeach    
		</select>

 </div>
 <div id="diverr_envelop_inside_id" text-danger></div>
</div>
<div class="col-md-6 mt-3">
	<div class="form-group">
    <label class="form-label" for="sound_file_id">SOUND FILE</label>

@php
    
    if(!Empty($row)){ 
        $selected = $row->sound_file_id; 
    }else{
        $selected = '';
    }
    $options = get_list_values('sound_files','title');
    //pre($options);
	//$options = $sound_file_id;
 @endphp

		 <select class="form-control" name="sound_file_id" id="sound_file_id"> 
		   <option value="">--Select--</option>
		   @foreach ($options as $key => $value)
			<option value="{{$key}}" {{($key == $selected) ? 'selected' : '' }}> 
				{{$value}} 
			</option>
		  @endforeach    
		</select>

 </div>
 <div id="diverr_sound_file_id" text-danger></div>
</div>
<div class="col-md-6 mt-3">
	<div class="form-group">
    <label class="form-label" for="effect_id">EFFECTS FILE</label>

@php
    
    if(!Empty($row)){ 
        $selected = $row->effect_id; 
    }else{
        $selected = '';
    }
    $options = get_list_values('effects','title');
    //pre($options);
	//$options = $effect_id;
 @endphp

		 <select class="form-control" name="effect_id" id="effect_id"> 
		   <option value="">--Select--</option>
		   @foreach ($options as $key => $value)
			<option value="{{$key}}" {{($key == $selected) ? 'selected' : '' }}> 
				{{$value}} 
			</option>
		  @endforeach    
		</select>

 </div>
 <div id="diverr_effect_id" text-danger></div>
</div>

<div class="col-md-6 mt-3">
	<div class="form-group">
		<label for='card_price' for="card_price">CARD PRICE</label>
		<input
			type="number"
			id="card_price"
			name="card_price"
			class="form-control"
		
			value="@if(isset($row->card_price)) {{ $row->card_price }} @endif"
			
		/>
		
	</div>
	<div id="diverr_card_price" text-danger></div>
</div>

<div class="col-md-6 mt-3">
	<div class="form-group">
    <label class="form-label" for="active">ACTIVE</label>

@php
    
    if(!Empty($row)){ 
        $selected = $row->active; 
    }else{
        $selected = '';
    }
    $options = get_list_values('active_status','is_active');
    //pre($options);
	//$options = $active;
 @endphp

		 <select class="form-control" name="active" id="active"> 
		   <option value="">--Select--</option>
		   @foreach ($options as $key => $value)
			<option value="{{$key}}" {{($key == $selected) ? 'selected' : '' }}> 
				{{$value}} 
			</option>
		  @endforeach    
		</select>

 </div>
 <div id="diverr_active" text-danger></div>
</div>

                                                
                                            </div>
                                            
                                            <input type="hidden" name="continue" id="continue" value="Y" />
                                            <input type="hidden" name="id" id="id" value="@if(isset($row->id)) {{id2str($row->id)}} @endif" />
                                            
                                </div>
                            </div>
                        </div>

                        <div class="card-footer">
                            <div class="row " > 
                                <div class="col-md-6 text-start mt-2">
                                    <button type="submit" class="btn btn-primary waves-effect waves-light w-md">Submit</button>
                                </div>
                                <div class="col-md-6 text-end  mt-2">
                                    <button type="reset" class="btn btn-outline-danger waves-effect waves-light w-md">Reset</button>
                                </div>
                            </div>
                        </div>
                        </form>
                    </div>
                </div>
            </div>

        </div> 
    </div>


@endsection