@extends('layouts.app')
@section('content')

{{-- ************************************************
         This file is generated by SNOOBIX on Aug 03, 2024
         Please visit snoobix.com for more details
         *********************************************** --}}

<div class="page-content">
	<div class="container-fluid">

		<div class="row">
			<div class="col-lg-12">
				<div class="card">
					<form action="{{route('backend.ticket_types.'.$submit_path)}}" method="POST" ENCTYPE="multipart/form-data">
						@csrf
						<div class="card-header">
							<div class="row">
								<div class="col-3 text-start">
									<div class="page-title-box d-flex align-items-center justify-content-between">
										<h4 class="card-title">{{ucwords($module_title)}} </h4>
									</div>
								</div>
								<div class="col-6 text-center">
									@if(session('flash_success') != '')
									<div class="alert alert-success">{{session('flash_success')}}</div>
									@endif
									@if(session('flash_failure') != '')
									<div class="alert alert-danger">{{session('flash_failure')}}</div>
									@endif
								</div>
								<div class="col-3 text-end">
									<a href="{{route('backend.ticket_types')}}" class="btn btn-info btn-md">List Page</a>
								</div>
							</div>
						</div>
						<div class="card-body">

							<div class="row">
								<div class="col-lg-12">


									<div class="row">


										<input type="hidden" id="id" name="id" value="@if(isset($row->id)) {{ $row->id }} @endif" />





										<input type="hidden" id="user_id" name="user_id" value="@if(isset($row->user_id)) {{ $row->user_id }} @endif" />





										<input type="hidden" id="web_user_id" name="web_user_id" value="@if(isset($row->web_user_id)) {{ $row->web_user_id }} @endif" />





										<div class="col-md-6 mt-3">
											<div class="form-group">
												<label class="form-label" for="ticket_image">TICKET IMAGE</label>
												<input type="file" id="ticket_image" name="ticket_image" class="form-control">

												<div>
													@if(isset($row) && !Empty($row))
													<img src="{{url('storage/'.str_replace('public/','',$row->ticket_image))}}" width="200px" height="250px" />
													@endif
												</div>

											</div>
											<div id="diverr_ticket_image" text-danger></div>
										</div>



										<div class="col-md-6 mt-3">
											<div class="form-group">
												<label class="form-label" for="ticket_type">TICKET TYPE</label>
												<input type="text" id="ticket_type" name="ticket_type" class="form-control" value="@if(isset($row->ticket_type)){{$row->ticket_type}}@endif" />
											</div>
											<div id="diverr_ticket_type" text-danger></div>
										</div>



										<div class="col-md-6 mt-3">
											<div class="form-group">
												<label for='tokens' for="tokens">TOKENS</label>
												<input type="number" id="tokens" name="tokens" class="form-control" value="{{ $row->tokens ?? 0}}" />

											</div>
											<div id="diverr_tokens" text-danger></div>
										</div>



										<div class="col-md-6 mt-3">
											<div class="form-group">
												<label class="form-label" for="short_descr">SHORT DESCR</label>
												<input type="text" id="short_descr" name="short_descr" class="form-control" value="@if(isset($row->short_descr)){{$row->short_descr}}@endif" />
											</div>
											<div id="diverr_short_descr" text-danger></div>
										</div>


										<div class="col-md-6 mt-3">
											<div class="form-group">
												<label class="form-label" for="active">ACTIVE</label>

												@php

												if(!Empty($row)){
												$selected = $row->active;
												}else{
												$selected = '';
												}
												$options = get_list_values('active_status','is_active');
												//pre($options);
												//$options = $active;
												@endphp

												<select class="form-control" name="active" id="active">
													<option value="">--Select--</option>
													@foreach ($options as $key => $value)
													<option value="{{$key}}" {{($key == $selected) ? 'selected' : '' }}>
														{{$value}}
													</option>
													@endforeach
												</select>

											</div>
											<div id="diverr_active" text-danger></div>
										</div>



									</div>

									<input type="hidden" name="continue" id="continue" value="Y" />
									<input type="hidden" name="id" id="id" value="@if(isset($row->id)) {{id2str($row->id)}} @endif" />

								</div>
							</div>
						</div>

						<div class="card-footer">
							<div class="row ">
								<div class="col-md-6 text-start mt-2">
									<button type="submit" class="btn btn-primary waves-effect waves-light w-md">Submit</button>
								</div>
								<div class="col-md-6 text-end  mt-2">
									<button type="reset" class="btn btn-outline-danger waves-effect waves-light w-md">Reset</button>
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>

	</div>
</div>


@endsection