@extends('layouts.app')
@section('content')

{{-- ************************************************
         This file is generated by SNOOBIX on May 16, 2024
         Please visit snoobix.com for more details
         *********************************************** --}}

<div class="page-content">
	<div class="container-fluid">

		<div class="row">
			<div class="col-lg-12">
				<div class="card">
					<form action="{{route('backend.users.'.$submit_path)}}" method="POST" ENCTYPE="multipart/form-data">
						@csrf
						<div class="card-header">
							<div class="row">
								<div class="col-3 text-start">
									<div class="page-title-box d-flex align-items-center justify-content-between">
										<h4 class="card-title">{{ucwords($module_title)}} </h4>
									</div>
								</div>
								<div class="col-6 text-center">
									@if(session('flash_success') != '')
									<div class="alert alert-success">{{session('flash_success')}}</div>
									@endif
									@if(session('flash_failure') != '')
									<div class="alert alert-danger">{{session('flash_failure')}}</div>
									@endif
								</div>
								<div class="col-3 text-end">
									<a href="{{route('backend.users')}}" class="btn btn-info btn-md">List Page</a>
								</div>
							</div>
						</div>
						<div class="card-body">

							<div class="row">
								<div class="col-lg-12">

									<div class="row">

										<input type="hidden" id="id" name="id" value="@if(isset($row->id)) {{ $row->id }} @endif" />

										<input type="hidden" id="user_id" name="user_id" value="@if(isset($row->user_id)) {{ $row->user_id }} @endif" />

										<input type="hidden" id="web_user_id" name="web_user_id" value="@if(isset($row->web_user_id)) {{ $row->web_user_id }} @endif" />

										<div class="col-md-6 mt-3">
											<div class="form-group">
												<label class="form-label" for="name">FULL NAME</label>
												<input type="text" id="name" name="name" class="form-control" value="@if(isset($row->name)){{$row->name}}@endif" required />
											</div>
											<div id="diverr_name" text-danger></div>
										</div>

										<div class="col-md-6 mt-3">
											<div class="form-group">
												<label class="form-label" for="email">EMAIL</label>
												<input type="text" id="email" name="email" class="form-control" value="@if(isset($row->email)){{$row->email}}@endif" required />
											</div>
											<div id="diverr_email" text-danger></div>
										</div>

										<div class="col-md-6 mt-3">
											<div class="form-group">
												<label class="form-label" for="email_verified_at">EMAIL VERIFIED AT</label>
												<input type="datetime-local" id="email_verified_at" name="email_verified_at" class="form-control" value="@if(isset($row->email_verified_at)) {{ $row->email_verified_at }} @endif" />

											</div>
											<div id="diverr_email_verified_at" text-danger></div>
										</div>

										<div class="col-md-6 mt-3">
											<div class="form-group">
												<label class="form-label" for="validation_code">VALIDATION CODE</label>
												<input type="text" id="validation_code" name="validation_code" class="form-control" value="@if(isset($row->validation_code)){{$row->validation_code}}@endif" />
											</div>
											<div id="diverr_validation_code" text-danger></div>
										</div>

										<div class="col-md-6 mt-3">
											<div class="form-group">
												<label class="form-label" for="password">PASSWORD</label>
												<input type="text" id="password" name="password" class="form-control" value="@if(isset($row->password)){{$row->password}}@endif" required />
											</div>
											<div id="diverr_password" text-danger></div>
										</div>

										<div class="col-md-6 mt-3">
											<div class="form-group">
												<label class="form-label" for="active">ACTIVE</label>

												@php

												if(!Empty($row)){
												$selected = $row->active;
												}else{
												$selected = '';
												}
												$options = get_list_values('active_status','is_active');
												//pre($options);
												//$options = $active;
												@endphp

												<select class="form-control" name="active" id="active">
													<option value="">--Select--</option>
													@foreach ($options as $key => $value)
													<option value="{{$key}}" {{($key == $selected) ? 'selected' : '' }}>
														{{$value}}
													</option>
													@endforeach
												</select>

											</div>
											<div id="diverr_active" text-danger></div>
										</div>

										<div class="col-md-6 mt-3">
											<div class="form-group">
												<label class="form-label" for="account_type">ACCOUNT TYPE</label>

												@php

												if(!Empty($row)){
												$selected = $row->account_type;
												}else{
												$selected = '';
												}
												$options = explode(',','Admin,User');
												//pre($options);
												//$options = $account_type;
												@endphp

												<select class="form-control" name="account_type" id="account_type">
													<option value="">--Select--</option>
													@foreach ($options as $key => $value)
													<option value="{{$key}}" {{($key == $selected) ? 'selected' : '' }}>
														{{$value}}
													</option>
													@endforeach
												</select>

											</div>
											<div id="diverr_account_type" text-danger></div>
										</div>

										<div class="col-md-6 mt-3">
											<div class="form-group">
												<label class="form-label" for="photo">PHOTO</label>
												<input type="file" id="photo" name="photo" class="form-control">

												<div>
													@if(isset($row) && !Empty($row))
													<img src="{{url('storage/'.str_replace('public/','',$row->photo))}}" width="200px" height="250px" />
													@endif
												</div>

											</div>
											<div id="diverr_photo" text-danger></div>
										</div>

										<div class="col-md-6 mt-3">
											<div class="form-group">
												<label class="form-label" for="country">COUNTRY</label>

												@php

												if(!Empty($row)){
												$selected = $row->country;
												}else{
												$selected = '';
												}
												$options = get_list_values('countries','country_name');
												//pre($options);
												//$options = $country;
												@endphp

												<select class="form-control" name="country" id="country">
													<option value="">--Select--</option>
													@foreach ($options as $key => $value)
													<option value="{{$key}}" {{($key == $selected) ? 'selected' : '' }}>
														{{$value}}
													</option>
													@endforeach
												</select>

											</div>
											<div id="diverr_country" text-danger></div>
										</div>

										<div class="col-md-6 mt-3">
											<div class="form-group">
												<label class="form-label" for="state">STATE</label>
												<input type="text" id="state" name="state" class="form-control" value="@if(isset($row->state)){{$row->state}}@endif" />
											</div>
											<div id="diverr_state" text-danger></div>
										</div>

										<div class="col-md-6 mt-3">
											<div class="form-group">
												<label class="form-label" for="city">CITY</label>
												<input type="text" id="city" name="city" class="form-control" value="@if(isset($row->city)){{$row->city}}@endif" />
											</div>
											<div id="diverr_city" text-danger></div>
										</div>

										<div class="col-md-12 mt-3">
											<div class="form-group">
												<label class="form-label" for="street_address">STREET ADDRESS</label>
												<textarea id="street_address" name="street_address" class="form-control">@if(isset($row->street_address)){{$row->street_address}}@endif</textarea>

											</div>
											<div id="diverr_street_address" text-danger></div>
										</div>

										<div class="col-md-6 mt-3">
											<div class="form-group">
												<label class="form-label" for="zip_post_code">ZIP POST CODE</label>
												<input type="text" id="zip_post_code" name="zip_post_code" class="form-control" value="@if(isset($row->zip_post_code)){{$row->zip_post_code}}@endif" />
											</div>
											<div id="diverr_zip_post_code" text-danger></div>
										</div>

										<div class="col-md-6 mt-3">
											<div class="form-group">
												<label class="form-label" for="phone">PHONE</label>
												<input type="text" id="phone" name="phone" class="form-control" value="@if(isset($row->phone)){{$row->phone}}@endif" />
											</div>
											<div id="diverr_phone" text-danger></div>
										</div>

										<div class="col-md-6 mt-3">
											<div class="form-group">
												<label class='form-check-label' for='agree_terms_condition'></label> &nbsp;&nbsp;
												<div class='form-check'>

													<input class="form-check-input" type="checkbox" name="agree_terms_condition" id="agree_terms_condition" value="Y" @if(!Empty($row)) @if($row->agree_terms_condition=='Y')
													checked="checked"
													@endif
													@endif
													>
													<label class='form-check-label' for='agree_terms_condition'>AGREE TERMS CONDITION</label>

												</div>
												<div id="diverr_agree_terms_condition" text-danger></div>
											</div>
										</div>

									</div>

									<input type="hidden" name="continue" id="continue" value="Y" />
									<input type="hidden" name="id" id="id" value="@if(isset($row->id)) {{id2str($row->id)}} @endif" />

								</div>
							</div>
						</div>

						<div class="card-footer">
							<div class="row ">
								<div class="col-md-6 text-start mt-2">
									<button type="submit" class="btn btn-primary waves-effect waves-light w-md">Submit</button>
								</div>
								<div class="col-md-6 text-end  mt-2">
									<button type="reset" class="btn btn-outline-danger waves-effect waves-light w-md">Reset</button>
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>

	</div>
</div>

@endsection