<?php

namespace App\Http\Controllers\Backend;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Models\sounds_model;


/* ******************************************************
    This file is generated by SNOOBIX on May 16, 2024
    Please visit snoobix.com for more details
****************************************************** */


class Sounds extends Controller
{
    public function __construct()
    {
        //if (!Auth::check()) return 'access_denied';
    }
   
    public function index()
    { 
        $data['module_title'] = 'Sounds';
		$data['rows'] = sounds_model::orderBy('id', 'desc')->get();
		return view("backend/sounds_list", $data);
	
    }


    public function create()
    {
        $data['module_title'] = 'Sounds';
       //$data['row'] = [];
       $data['submit_path'] = 'store';
       $data['module_name'] = 'Sounds';
       return view("backend/sounds_addedit", $data);       
    }

   
    public function store(Request $request)
    {
         $data['module_title'] = 'Sounds';
        /* $request->validate([
            [[validateFieldsArray]]
        ]); */

        /* $record = [
			[[fieldsArray]]
		];
		$iscreated = sounds_model::create($record); */

        $record = $request->all();
        
        
        $savedid = sounds_model::create($record)->id;
		if($savedid){
			 //return view("backend/sounds_addedit")->with('flash_success', "Record is saved successfuly");
             return redirect('backend/sounds/create')->with('flash_success', "Record is saved successfuly");
		}else{
			$data['row'] = $request->all();
			return view("backend/sounds_addedit", $data)->with('flash_failure', "Record is NOT saved successfuly");
		}
    }

    
    public function show()
    {
        //
    }

    
    public function edit($id)
    {
         $data['module_title'] = 'Sounds';
        $data['submit_path'] = 'update';
        $recCond = [
			'id' => str2id($id)
		];
		$data['row'] = sounds_model::where($recCond)->first();
		return view("backend/sounds_addedit", $data);
    }

   
    public function update(Request $request)
    {
		 $data['module_title'] = 'Sounds';
        $id = $request->post('id');
        $id = str2id($id);
        $vsounds_model = sounds_model::find($id);
        
         $record = $request->all();
         
        
        $isaved = $vsounds_model->fill($record)->save();  //this will save record with all fillable items

        if($isaved){
			//return view("backend/sounds_addedit")->with('flash_success', "Record is updated successfuly");
            return redirect('backend/sounds')->with('flash_success', "Record is updated successfuly");
		}else{

			//$data['postData'] = $record;
             $data['submit_path'] = 'update';
             $recCond = [
                'id' => $id,
            ];
            $data['row'] = sounds_model::where($recCond)->first();
			return view("backend/sounds_addedit", $data)->with('flash_failure', "Record is NOT updated successfuly");
		}		
    }

   
    public function destroy(Request $request)
    {
        $id = $request->post('delid');
        $id = str2id($id);
        $vsounds_model = sounds_model::find($id);
        $isdeleted = $vsounds_model->delete();
        if($isdeleted ){
            return redirect()->route('backend.sounds')->with('flash_success','Record is deleted successfuly');
        }else{
            return redirect()->route('backend.sounds')->with('flash_failure','Record is not deleted, try again later');
        }
    }
}
